//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encryptics.WebPortal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Encryptics.WebPortal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation failed..
        /// </summary>
        public static string AccountActivationFailedErrorMessage {
            get {
                return ResourceManager.GetString("AccountActivationFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation failed. Please try again..
        /// </summary>
        public static string AccountActivationFailedTryAgainMessage {
            get {
                return ResourceManager.GetString("AccountActivationFailedTryAgainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link you followed to activate your account is invalid..
        /// </summary>
        public static string AccountActivationStatusBadDataErrorMessage {
            get {
                return ResourceManager.GetString("AccountActivationStatusBadDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link you followed to activate your account has expired..
        /// </summary>
        public static string AccountActivationStatusExpiredErrorMessage {
            get {
                return ResourceManager.GetString("AccountActivationStatusExpiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to verify the validity of the link you followed to activate your account has failed for unknown reasons..
        /// </summary>
        public static string AccountActivationStatusFailedErrorMessage {
            get {
                return ResourceManager.GetString("AccountActivationStatusFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link you followed to activate your account is no longer valid as the account you are attempting to activate has been removed..
        /// </summary>
        public static string AccountActivationStatusRemovedErrorMessage {
            get {
                return ResourceManager.GetString("AccountActivationStatusRemovedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link you followed to activate your account has already been used. Your account is fully active at this time. If you feel this is in error please contact support..
        /// </summary>
        public static string AccountActivationStatusUsedErrorMessage {
            get {
                return ResourceManager.GetString("AccountActivationStatusUsedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! You&apos;re now registered. You should receive an activation email. If you&apos;ve already activated proceed to log on..
        /// </summary>
        public static string AccountAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("AccountAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details could not be updated..
        /// </summary>
        public static string AccountDetailsNotUpdatedErrorMessage {
            get {
                return ResourceManager.GetString("AccountDetailsNotUpdatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string AccountLicenseTypeFree {
            get {
                return ResourceManager.GetString("AccountLicenseTypeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string AccountLicenseTypeProfessional {
            get {
                return ResourceManager.GetString("AccountLicenseTypeProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string AccountLicenseTypeTrial {
            get {
                return ResourceManager.GetString("AccountLicenseTypeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! You&apos;re now registered. You should receive an activation email. If you&apos;ve already activated proceed to log on..
        /// </summary>
        public static string AccountMayAlreadyBeActivatedErrorMessage {
            get {
                return ResourceManager.GetString("AccountMayAlreadyBeActivatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string AccountStatusDisplay {
            get {
                return ResourceManager.GetString("AccountStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We experienced an internal error on our side. Your account should be created at this time. If you do not receive an activation email please try registering again..
        /// </summary>
        public static string ActivationTimeOutErrorMessage {
            get {
                return ResourceManager.GetString("ActivationTimeOutErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation was successfull but log in failed..
        /// </summary>
        public static string ActivationWasSuccessfullButLogInFailedMessage {
            get {
                return ResourceManager.GetString("ActivationWasSuccessfullButLogInFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveDisplay {
            get {
                return ResourceManager.GetString("ActiveDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please agree to Terms and Conditions.
        /// </summary>
        public static string AgreeToTermsErrorMessage {
            get {
                return ResourceManager.GetString("AgreeToTermsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer your secret question..
        /// </summary>
        public static string AnswerSecretQuestionMessage {
            get {
                return ResourceManager.GetString("AnswerSecretQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-my-custom-header.
        /// </summary>
        public static string AuthenticationTicketHeaderName {
            get {
                return ResourceManager.GetString("AuthenticationTicketHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string ChangePasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company.
        /// </summary>
        public static string CompanyNameDisplay {
            get {
                return ResourceManager.GetString("CompanyNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string CompanySummaryModel_EncrypticsUsage_Usage {
            get {
                return ResourceManager.GetString("CompanySummaryModel_EncrypticsUsage_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Accounts.
        /// </summary>
        public static string CompanySummaryModel_PendingAccounts_Pending_Accounts {
            get {
                return ResourceManager.GetString("CompanySummaryModel_PendingAccounts_Pending_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Accounts.
        /// </summary>
        public static string CompanySummaryModel_UserAccounts_User_Accounts {
            get {
                return ResourceManager.GetString("CompanySummaryModel_UserAccounts_User_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPasswordDisplay {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPasswordDisplay {
            get {
                return ResourceManager.GetString("ConfirmPasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations your account has been successfully activated..
        /// </summary>
        public static string CongratulationsAccountActivatedMessage {
            get {
                return ResourceManager.GetString("CongratulationsAccountActivatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not activate this device..
        /// </summary>
        public static string CouldNotActivateDeviceErrorMessage {
            get {
                return ResourceManager.GetString("CouldNotActivateDeviceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deactivate this device..
        /// </summary>
        public static string CouldNotDeactivateDeviceErrorMessage {
            get {
                return ResourceManager.GetString("CouldNotDeactivateDeviceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deactivate the session for this device..
        /// </summary>
        public static string CouldNotDeactivateDeviceSessionErrorMessage {
            get {
                return ResourceManager.GetString("CouldNotDeactivateDeviceSessionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log new user in..
        /// </summary>
        public static string CouldNotLogNewUserInMessage {
            get {
                return ResourceManager.GetString("CouldNotLogNewUserInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove this device for this user..
        /// </summary>
        public static string CouldNotRemoveDeviceErrorMessage {
            get {
                return ResourceManager.GetString("CouldNotRemoveDeviceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not re-send Account Activation Link!.
        /// </summary>
        public static string CouldNotResendActivationMessage {
            get {
                return ResourceManager.GetString("CouldNotResendActivationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve your account details.
        /// </summary>
        public static string CouldNotRetrieveAccountDetailsErrorMessage {
            get {
                return ResourceManager.GetString("CouldNotRetrieveAccountDetailsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve company names..
        /// </summary>
        public static string CouldNotRetrieveCompanyNamesMessage {
            get {
                return ResourceManager.GetString("CouldNotRetrieveCompanyNamesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve devices. Please try again. If this problem persists contact support..
        /// </summary>
        public static string CouldNotRetrieveDevicesErrorMessage {
            get {
                return ResourceManager.GetString("CouldNotRetrieveDevicesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve user account.
        /// </summary>
        public static string CouldNotRetrieveUserAccount {
            get {
                return ResourceManager.GetString("CouldNotRetrieveUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update account details (server error)..
        /// </summary>
        public static string CouldNotUpdateUserAccountErrorMessage {
            get {
                return ResourceManager.GetString("CouldNotUpdateUserAccountErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not verify current password..
        /// </summary>
        public static string CouldNotVerifyPasswordErrorMessage {
            get {
                return ResourceManager.GetString("CouldNotVerifyPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPasswordDisplay {
            get {
                return ResourceManager.GetString("CurrentPasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string CurrentPasswordIsIncorrectOrTheNewPasswordIsInvalidMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordIsIncorrectOrTheNewPasswordIsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Current password field is required..
        /// </summary>
        public static string CurrentPasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Applied.
        /// </summary>
        public static string DateLicenseCreatedDisplay {
            get {
                return ResourceManager.GetString("DateLicenseCreatedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expires on.
        /// </summary>
        public static string DateLicenseExpiresDisplay {
            get {
                return ResourceManager.GetString("DateLicenseExpiresDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Applied.
        /// </summary>
        public static string DateLinceseCreated {
            get {
                return ResourceManager.GetString("DateLinceseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed.
        /// </summary>
        public static string DatePasswordChangedDisplay {
            get {
                return ResourceManager.GetString("DatePasswordChangedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registered on.
        /// </summary>
        public static string DateRegisteredDisplay {
            get {
                return ResourceManager.GetString("DateRegisteredDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuspend.
        /// </summary>
        public static string DeviceListPartialActivateDisplay {
            get {
                return ResourceManager.GetString("DeviceListPartialActivateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string DeviceListPartialSuspendDisplay {
            get {
                return ResourceManager.GetString("DeviceListPartialSuspendDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added:.
        /// </summary>
        public static string DevicePartialAddedDisplay {
            get {
                return ResourceManager.GetString("DevicePartialAddedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forget.
        /// </summary>
        public static string DevicePartialForgetDeviceDisplay {
            get {
                return ResourceManager.GetString("DevicePartialForgetDeviceDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string DevicePartialLogoutDisplay {
            get {
                return ResourceManager.GetString("DevicePartialLogoutDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string DevicePartialServerErrorDisplay {
            get {
                return ResourceManager.GetString("DevicePartialServerErrorDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suspended.
        /// </summary>
        public static string DevicePartialSuspendedDisplay {
            get {
                return ResourceManager.GetString("DevicePartialSuspendedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Devices.
        /// </summary>
        public static string DevicesPartalNoDevicesHeading {
            get {
                return ResourceManager.GetString("DevicesPartalNoDevicesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float: left;.
        /// </summary>
        public static string DevicesPartialLaptopImageStyle {
            get {
                return ResourceManager.GetString("DevicesPartialLaptopImageStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to {0} for Email from a computer or mobile device. Manage any of your {0} devices right from this website..
        /// </summary>
        public static string DevicesPartialNoDevicesInstructions {
            get {
                return ResourceManager.GetString("DevicesPartialNoDevicesInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string DisplayFirstName {
            get {
                return ResourceManager.GetString("DisplayFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string DisplayLastName {
            get {
                return ResourceManager.GetString("DisplayLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        public static string DisplayRisk {
            get {
                return ResourceManager.GetString("DisplayRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By.
        /// </summary>
        public static string DisplaySearchBy {
            get {
                return ResourceManager.GetString("DisplaySearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for.
        /// </summary>
        public static string DisplaySearchFor {
            get {
                return ResourceManager.GetString("DisplaySearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Violations.
        /// </summary>
        public static string DisplayTotalViolations {
            get {
                return ResourceManager.GetString("DisplayTotalViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string DownloadsPartialAndroidHeading {
            get {
                return ResourceManager.GetString("DownloadsPartialAndroidHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS.
        /// </summary>
        public static string DownloadsPartialiOSHeading {
            get {
                return ResourceManager.GetString("DownloadsPartialiOSHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac.
        /// </summary>
        public static string DownloadsPartialMacHeading {
            get {
                return ResourceManager.GetString("DownloadsPartialMacHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for Email.
        /// </summary>
        public static string DownloadsPartialTitle {
            get {
                return ResourceManager.GetString("DownloadsPartialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string DownloadsPartialWindowsHeading {
            get {
                return ResourceManager.GetString("DownloadsPartialWindowsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string EmailAddressDisplay {
            get {
                return ResourceManager.GetString("EmailAddressDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is required..
        /// </summary>
        public static string EmailAddressRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailAddressRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password again..
        /// </summary>
        public static string EnterPasswordAgainMessage {
            get {
                return ResourceManager.GetString("EnterPasswordAgainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user name or {0} email address..
        /// </summary>
        public static string EnterUserNameMessage {
            get {
                return ResourceManager.GetString("EnterUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot log in at this time. Your account has been locked out. Your administrator can unlock your account..
        /// </summary>
        public static string ErrorMessageAccontLockedOut {
            get {
                return ResourceManager.GetString("ErrorMessageAccontLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve pending accounts..
        /// </summary>
        public static string ErrorMessageCouldNotRetreivePendingAccounts {
            get {
                return ResourceManager.GetString("ErrorMessageCouldNotRetreivePendingAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve active accounts..
        /// </summary>
        public static string ErrorMessageCouldNotRetrieveActiveAccounts {
            get {
                return ResourceManager.GetString("ErrorMessageCouldNotRetrieveActiveAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve company details!.
        /// </summary>
        public static string ErrorMessageCouldNotRetrieveCompanyDetails {
            get {
                return ResourceManager.GetString("ErrorMessageCouldNotRetrieveCompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve entity details..
        /// </summary>
        public static string ErrorMessageCouldNotRetrieveEntityDetails {
            get {
                return ResourceManager.GetString("ErrorMessageCouldNotRetrieveEntityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retreive suspended accounts..
        /// </summary>
        public static string ErrorMessageCouldNotRetrieveSuspendedAccounts {
            get {
                return ResourceManager.GetString("ErrorMessageCouldNotRetrieveSuspendedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate CAPTCHA..
        /// </summary>
        public static string ErrorMessageCouldNotValidateCaptcha {
            get {
                return ResourceManager.GetString("ErrorMessageCouldNotValidateCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log in to server. Please try again later or contact customer support..
        /// </summary>
        public static string ErrorMessageCoultNotLogIn {
            get {
                return ResourceManager.GetString("ErrorMessageCoultNotLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter an email address, first or last name..
        /// </summary>
        public static string ErrorMessageMustEnterEmail {
            get {
                return ResourceManager.GetString("ErrorMessageMustEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be atleast 8 characters long, contain atleast one lower case letter, one uppercase letter and one digit..
        /// </summary>
        public static string ErrorMessagePasswordFormat {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please go back and try again. If this problem persists, &lt;a href=&quot;mailto:{0}&quot;&gt;contact us&lt;/a&gt;..
        /// </summary>
        public static string ErrorRegisteringAccountMessage {
            get {
                return ResourceManager.GetString("ErrorRegisteringAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending Account Activation Link!.
        /// </summary>
        public static string ErrorSendingAccountActivationMessage {
            get {
                return ResourceManager.GetString("ErrorSendingAccountActivationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing Agreement.
        /// </summary>
        public static string EulaAcceptanceDisplay {
            get {
                return ResourceManager.GetString("EulaAcceptanceDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        public static string FirstNameDisplay {
            get {
                return ResourceManager.GetString("FirstNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name must be 50 letters or less..
        /// </summary>
        public static string FirstNameLengthErrorMessage {
            get {
                return ResourceManager.GetString("FirstNameLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address below and click the submit button. You will receive an email with a link. If you click on that link you can then create a new password..
        /// </summary>
        public static string ForgotPasswordPartialInstructions {
            get {
                return ResourceManager.GetString("ForgotPasswordPartialInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image by Gravatar.
        /// </summary>
        public static string GravatarImageText {
            get {
                return ResourceManager.GetString("GravatarImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string InactiveDisplay {
            get {
                return ResourceManager.GetString("InactiveDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address format.
        /// </summary>
        public static string InvalidEmailAddressFormatErrorMessage {
            get {
                return ResourceManager.GetString("InvalidEmailAddressFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string LastNameDisplay {
            get {
                return ResourceManager.GetString("LastNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name must be 50 letters or less..
        /// </summary>
        public static string LastNameLengthErrorMessage {
            get {
                return ResourceManager.GetString("LastNameLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string LicenseTypeDisplay {
            get {
                return ResourceManager.GetString("LicenseTypeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        public static string ManagePasswordPartialTitle {
            get {
                return ResourceManager.GetString("ManagePasswordPartialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string MembershipDefaultUnknownErrorMessage {
            get {
                return ResourceManager.GetString("MembershipDefaultUnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string MembershipDuplicateEmailErrorMessage {
            get {
                return ResourceManager.GetString("MembershipDuplicateEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MembershipInvalidAnswerErrorMessage {
            get {
                return ResourceManager.GetString("MembershipInvalidAnswerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MembershipInvalidEmailErrorMessage {
            get {
                return ResourceManager.GetString("MembershipInvalidEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string MembershipInvalidPasswordErrorMessage {
            get {
                return ResourceManager.GetString("MembershipInvalidPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MembershipInvalidQuestionErrorMessage {
            get {
                return ResourceManager.GetString("MembershipInvalidQuestionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MembershipInvalidUserNameErrorMessage {
            get {
                return ResourceManager.GetString("MembershipInvalidUserNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string MembershipProviderErrorErrorMessage {
            get {
                return ResourceManager.GetString("MembershipProviderErrorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string MembershipUserRejectedErrorMessage {
            get {
                return ResourceManager.GetString("MembershipUserRejectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Portal.
        /// </summary>
        public static string MenuAdminPortal {
            get {
                return ResourceManager.GetString("MenuAdminPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string MenuChangePassword {
            get {
                return ResourceManager.GetString("MenuChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Software.
        /// </summary>
        public static string MenuDownloadSoftware {
            get {
                return ResourceManager.GetString("MenuDownloadSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string MenuLogIn {
            get {
                return ResourceManager.GetString("MenuLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string MenuLogOut {
            get {
                return ResourceManager.GetString("MenuLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string MenuManageAccount {
            get {
                return ResourceManager.GetString("MenuManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string MenuRegister {
            get {
                return ResourceManager.GetString("MenuRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string NameDisplay {
            get {
                return ResourceManager.GetString("NameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPasswordDisplay {
            get {
                return ResourceManager.GetString("NewPasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New password field is required..
        /// </summary>
        public static string NewPasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NewPasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoDisplay {
            get {
                return ResourceManager.GetString("NoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to change password was successful. Check your email and folow the link to update your password..
        /// </summary>
        public static string PasswordChangeSuccessfullMessage {
            get {
                return ResourceManager.GetString("PasswordChangeSuccessfullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password could not be updated..
        /// </summary>
        public static string PasswordCouldNotBeUpdatedMessage {
            get {
                return ResourceManager.GetString("PasswordCouldNotBeUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordDisplay {
            get {
                return ResourceManager.GetString("PasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordMinimumLengthErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMinimumLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordNotMatchingErrorMessage {
            get {
                return ResourceManager.GetString("PasswordNotMatchingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect..
        /// </summary>
        public static string PasswordProvidedIsIncorrectMessage {
            get {
                return ResourceManager.GetString("PasswordProvidedIsIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required..
        /// </summary>
        public static string PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password could not be updated..
        /// </summary>
        public static string PasswordResetErrorMessage {
            get {
                return ResourceManager.GetString("PasswordResetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset request was unsuccessful..
        /// </summary>
        public static string PasswordResetUnsuccessfulErrorMessage {
            get {
                return ResourceManager.GetString("PasswordResetUnsuccessfulErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was successfully updated. Please try logging in again..
        /// </summary>
        public static string PasswordSuccessfullyUpdatedMessage {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you haven’t received an activation link in your email, click the button below to resend it..
        /// </summary>
        public static string PleaseResendActivationMessage {
            get {
                return ResourceManager.GetString("PleaseResendActivationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new {0} account name is.
        /// </summary>
        public static string PopoverAccountActivatedTabHeadingText {
            get {
                return ResourceManager.GetString("PopoverAccountActivatedTabHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are ready to begin using {0} software..
        /// </summary>
        public static string PopoverAccountActivatedTabPara1 {
            get {
                return ResourceManager.GetString("PopoverAccountActivatedTabPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may now &lt;a href=&quot;#&quot; class=&quot;closePopover&quot;&gt;close&lt;/a&gt; this window or &lt;a href=&quot;#&quot; class=&quot;showAccount&quot;&gt;view&lt;/a&gt; your account details..
        /// </summary>
        public static string PopoverAccountActivatedTabPara2 {
            get {
                return ResourceManager.GetString("PopoverAccountActivatedTabPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this account you can begin using {0} software..
        /// </summary>
        public static string PopoverAccountActivatedTabPara3 {
            get {
                return ResourceManager.GetString("PopoverAccountActivatedTabPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for Activating Your Account.
        /// </summary>
        public static string PopoverAccountActivatedTabTitle {
            get {
                return ResourceManager.GetString("PopoverAccountActivatedTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string PopoverAccountTabConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("PopoverAccountTabConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string PopoverAccountTabEmailAddressLabel {
            get {
                return ResourceManager.GetString("PopoverAccountTabEmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required..
        /// </summary>
        public static string PopoverAccountTabFieldsRequiredNote {
            get {
                return ResourceManager.GetString("PopoverAccountTabFieldsRequiredNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address format.
        /// </summary>
        public static string PopoverAccountTabInvalidEmailErrorMessage {
            get {
                return ResourceManager.GetString("PopoverAccountTabInvalidEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must match the password.
        /// </summary>
        public static string PopoverAccountTabMatchPasswordErrorMessage {
            get {
                return ResourceManager.GetString("PopoverAccountTabMatchPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PopoverAccountTabPasswordLabel {
            get {
                return ResourceManager.GetString("PopoverAccountTabPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least 8 character..
        /// </summary>
        public static string PopoverAccountTabPasswordLengthError {
            get {
                return ResourceManager.GetString("PopoverAccountTabPasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string PopoverAccountTabRegisterButtonLabel {
            get {
                return ResourceManager.GetString("PopoverAccountTabRegisterButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string PopoverAccountTabRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PopoverAccountTabRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to &lt;a href=&quot;#&quot;&gt;Terms &amp; Conditions&lt;/a&gt;.
        /// </summary>
        public static string PopoverAccountTabTermsLabel {
            get {
                return ResourceManager.GetString("PopoverAccountTabTermsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        public static string PopoverAccountTabTitle {
            get {
                return ResourceManager.GetString("PopoverAccountTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are almost done. Please wait while we activate your account..
        /// </summary>
        public static string PopoverActivateTabAlmostDoneText {
            get {
                return ResourceManager.GetString("PopoverActivateTabAlmostDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &lt;email address&gt;.
        /// </summary>
        public static string PopoverActivateTabCheckAccountDisplay {
            get {
                return ResourceManager.GetString("PopoverActivateTabCheckAccountDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you have successfully created an {0} account. We sent an activation link to your registered email address. Click the link in the email we sent to activate your account..
        /// </summary>
        public static string PopoverActivateTabCongratulationsText {
            get {
                return ResourceManager.GetString("PopoverActivateTabCongratulationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are having trouble, &lt;a href=&quot;#&quot;&gt;contact us&lt;/a&gt;..
        /// </summary>
        public static string PopoverActivateTabContactUsDisplay {
            get {
                return ResourceManager.GetString("PopoverActivateTabContactUsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for an activation link..
        /// </summary>
        public static string PopoverActivateTabForAnActivationLinkDisplay {
            get {
                return ResourceManager.GetString("PopoverActivateTabForAnActivationLinkDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resend activation.
        /// </summary>
        public static string PopoverActivateTabResendButtonText {
            get {
                return ResourceManager.GetString("PopoverActivateTabResendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Your Account.
        /// </summary>
        public static string PopoverActivateTabTitle {
            get {
                return ResourceManager.GetString("PopoverActivateTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email? Check your spam folder or try resending the activation link..
        /// </summary>
        public static string PopoverActivateTabTryResendingDisplay {
            get {
                return ResourceManager.GetString("PopoverActivateTabTryResendingDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create password.
        /// </summary>
        public static string PopoverCreatePasswordTabCreatePasswordButtonText {
            get {
                return ResourceManager.GetString("PopoverCreatePasswordTabCreatePasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your administrator has created an Encryptics acount for you using your email address..
        /// </summary>
        public static string PopoverCreatePasswordTabPara1 {
            get {
                return ResourceManager.GetString("PopoverCreatePasswordTabPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a password to activate your account..
        /// </summary>
        public static string PopoverCreatePasswordTabPara2 {
            get {
                return ResourceManager.GetString("PopoverCreatePasswordTabPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string PopoverCreatePasswordTabTitle {
            get {
                return ResourceManager.GetString("PopoverCreatePasswordTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view your account.
        /// </summary>
        public static string PopoverDoneAccountButtonText {
            get {
                return ResourceManager.GetString("PopoverDoneAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close this window.
        /// </summary>
        public static string PopoverDoneCloseButtonText {
            get {
                return ResourceManager.GetString("PopoverDoneCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the installer did not automatically download click here.
        /// </summary>
        public static string PopoverDoneDownloadManually {
            get {
                return ResourceManager.GetString("PopoverDoneDownloadManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thank you for downloading {0}!.
        /// </summary>
        public static string PopoverDoneTabTitle {
            get {
                return ResourceManager.GetString("PopoverDoneTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to App Store.
        /// </summary>
        public static string PopoverDownloadsTabAppStoreText {
            get {
                return ResourceManager.GetString("PopoverDownloadsTabAppStoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to google play.
        /// </summary>
        public static string PopoverDownloadsTabGooglePlayText {
            get {
                return ResourceManager.GetString("PopoverDownloadsTabGooglePlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software will begin downloading shortly..
        /// </summary>
        public static string PopoverDownloadsTabHeading {
            get {
                return ResourceManager.GetString("PopoverDownloadsTabHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the link below to install the software on your phone..
        /// </summary>
        public static string PopoverDownloadsTabInstallPhoneText {
            get {
                return ResourceManager.GetString("PopoverDownloadsTabInstallPhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to skip the download.
        /// </summary>
        public static string PopoverDownloadsTabSkipDownloadText {
            get {
                return ResourceManager.GetString("PopoverDownloadsTabSkipDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account is Now Activated.
        /// </summary>
        public static string PopoverDownloadsTabTitle {
            get {
                return ResourceManager.GetString("PopoverDownloadsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string PopoverTabHeadingAccount {
            get {
                return ResourceManager.GetString("PopoverTabHeadingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string PopoverTabHeadingActivate {
            get {
                return ResourceManager.GetString("PopoverTabHeadingActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string PopoverTabHeadingDevices {
            get {
                return ResourceManager.GetString("PopoverTabHeadingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string PopoverTabHeadingDone {
            get {
                return ResourceManager.GetString("PopoverTabHeadingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string PopoverTabHeadingDownload {
            get {
                return ResourceManager.GetString("PopoverTabHeadingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string PopoverTabHeadingDownloads {
            get {
                return ResourceManager.GetString("PopoverTabHeadingDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PopoverTabHeadingPassword {
            get {
                return ResourceManager.GetString("PopoverTabHeadingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string PopoverTabHeadingUsage {
            get {
                return ResourceManager.GetString("PopoverTabHeadingUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prev.
        /// </summary>
        public static string PreviousPageText {
            get {
                return ResourceManager.GetString("PreviousPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMeDisplay {
            get {
                return ResourceManager.GetString("RememberMeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string RemoveLoginSuccessMessage {
            get {
                return ResourceManager.GetString("RemoveLoginSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can &lt;a href=&quot;ForgotPassword.aspx&quot;&gt;request&lt;/a&gt; a new link to reset your password..
        /// </summary>
        public static string ResetPasswordErrorInstructions {
            get {
                return ResourceManager.GetString("ResetPasswordErrorInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link you followed to reset your password is invalid..
        /// </summary>
        public static string ResetPasswordLinkStatusBadDataErrorMessage {
            get {
                return ResourceManager.GetString("ResetPasswordLinkStatusBadDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link you followed to reset your password has expired..
        /// </summary>
        public static string ResetPasswordLinkStatusExpiredErrorMessage {
            get {
                return ResourceManager.GetString("ResetPasswordLinkStatusExpiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to verify the validity of the link you followed to reset your password has failed for unknown reasons..
        /// </summary>
        public static string ResetPasswordLinkStatusFailedErrorMessage {
            get {
                return ResourceManager.GetString("ResetPasswordLinkStatusFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link you followed to reset your password has already been used. .
        /// </summary>
        public static string ResetPasswordLinkStatusUsedErrorMessage {
            get {
                return ResourceManager.GetString("ResetPasswordLinkStatusUsedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password and click the submit button to reset your password..
        /// </summary>
        public static string ResetPasswordPartialInsructions {
            get {
                return ResourceManager.GetString("ResetPasswordPartialInsructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.
        /// </summary>
        public static string RoleDisplay {
            get {
                return ResourceManager.GetString("RoleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string RoleDropDown_User {
            get {
                return ResourceManager.GetString("RoleDropDown_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string SecretQuestionAnswerDisplay {
            get {
                return ResourceManager.GetString("SecretQuestionAnswerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Question.
        /// </summary>
        public static string SecretQuestionDisplay7 {
            get {
                return ResourceManager.GetString("SecretQuestionDisplay7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your childhood nickname?.
        /// </summary>
        public static string SecurityQuestion1 {
            get {
                return ResourceManager.GetString("SecurityQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where were you when you had your first kiss?.
        /// </summary>
        public static string SecurityQuestion10 {
            get {
                return ResourceManager.GetString("SecurityQuestion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the first name of the person that you first kissed?.
        /// </summary>
        public static string SecurityQuestion11 {
            get {
                return ResourceManager.GetString("SecurityQuestion11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the last name of your third grade teacher?.
        /// </summary>
        public static string SecurityQuestion12 {
            get {
                return ResourceManager.GetString("SecurityQuestion12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what city does your nearest sibling live?.
        /// </summary>
        public static string SecurityQuestion13 {
            get {
                return ResourceManager.GetString("SecurityQuestion13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your spouse&apos;s mother&apos;s maiden name?.
        /// </summary>
        public static string SecurityQuestion14 {
            get {
                return ResourceManager.GetString("SecurityQuestion14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what city or town was your first job?.
        /// </summary>
        public static string SecurityQuestion15 {
            get {
                return ResourceManager.GetString("SecurityQuestion15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of the place your wedding reception was held?.
        /// </summary>
        public static string SecurityQuestion16 {
            get {
                return ResourceManager.GetString("SecurityQuestion16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of a college you applied to but didn&apos;t attend?.
        /// </summary>
        public static string SecurityQuestion17 {
            get {
                return ResourceManager.GetString("SecurityQuestion17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where were you when you first heard about 9/11?.
        /// </summary>
        public static string SecurityQuestion18 {
            get {
                return ResourceManager.GetString("SecurityQuestion18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer #1.
        /// </summary>
        public static string SecurityQuestion1AnswerDisplay {
            get {
                return ResourceManager.GetString("SecurityQuestion1AnswerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question &amp; Answer #1.
        /// </summary>
        public static string SecurityQuestion1Display {
            get {
                return ResourceManager.GetString("SecurityQuestion1Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what city did you meet your spouse/significant other?.
        /// </summary>
        public static string SecurityQuestion2 {
            get {
                return ResourceManager.GetString("SecurityQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer #2.
        /// </summary>
        public static string SecurityQuestion2AnswerDisplay {
            get {
                return ResourceManager.GetString("SecurityQuestion2AnswerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question &amp; Answer #2.
        /// </summary>
        public static string SecurityQuestion2Display {
            get {
                return ResourceManager.GetString("SecurityQuestion2Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of your favorite childhood friend?.
        /// </summary>
        public static string SecurityQuestion3 {
            get {
                return ResourceManager.GetString("SecurityQuestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer #3.
        /// </summary>
        public static string SecurityQuestion3AnswerDisplay {
            get {
                return ResourceManager.GetString("SecurityQuestion3AnswerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question &amp; Answer #3.
        /// </summary>
        public static string SecurityQuestion3Display {
            get {
                return ResourceManager.GetString("SecurityQuestion3Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What street did you live on in third grade?.
        /// </summary>
        public static string SecurityQuestion4 {
            get {
                return ResourceManager.GetString("SecurityQuestion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the middle name of your oldest child?.
        /// </summary>
        public static string SecurityQuestion5 {
            get {
                return ResourceManager.GetString("SecurityQuestion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your oldest sibling&apos;s middle name?.
        /// </summary>
        public static string SecurityQuestion6 {
            get {
                return ResourceManager.GetString("SecurityQuestion6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What school did you attend for sixth grade?.
        /// </summary>
        public static string SecurityQuestion7 {
            get {
                return ResourceManager.GetString("SecurityQuestion7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your oldest cousin&apos;s first and last name?.
        /// </summary>
        public static string SecurityQuestion8 {
            get {
                return ResourceManager.GetString("SecurityQuestion8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what city or town did your mother and father meet?.
        /// </summary>
        public static string SecurityQuestion9 {
            get {
                return ResourceManager.GetString("SecurityQuestion9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string SetPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("SetPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string SubmitDisplay {
            get {
                return ResourceManager.GetString("SubmitDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string SuspendedDisplay {
            get {
                return ResourceManager.GetString("SuspendedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string UsageSummaryDayDisplay {
            get {
                return ResourceManager.GetString("UsageSummaryDayDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypts.
        /// </summary>
        public static string UsageSummaryDecryptsDisplay {
            get {
                return ResourceManager.GetString("UsageSummaryDecryptsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypts.
        /// </summary>
        public static string UsageSummaryEncryptsDisplay {
            get {
                return ResourceManager.GetString("UsageSummaryEncryptsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string UsageSummaryMonthDisplay {
            get {
                return ResourceManager.GetString("UsageSummaryMonthDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Usage Yet.
        /// </summary>
        public static string UsageSummaryNoUsageYet {
            get {
                return ResourceManager.GetString("UsageSummaryNoUsageYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        public static string UsageSummaryPartialDisplay {
            get {
                return ResourceManager.GetString("UsageSummaryPartialDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Usage.
        /// </summary>
        public static string UsageSummaryTitle {
            get {
                return ResourceManager.GetString("UsageSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string UsageSummaryYearDisplay {
            get {
                return ResourceManager.GetString("UsageSummaryYearDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string UserNameDisplay {
            get {
                return ResourceManager.GetString("UserNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string UserNameExistsMessage {
            get {
                return ResourceManager.GetString("UserNameExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesDisplay {
            get {
                return ResourceManager.GetString("YesDisplay", resourceCulture);
            }
        }
    }
}
